config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :doubles do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: :drestroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :double
end

app/models/double.rb
class Double < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :name, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :available, inclusion: { in: [ true, false ] }
  validates :price_per_day, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :doubles
  has_many :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :country, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/doubles_controller.rb
class DoublesController < ApplicationController
  def index
    @doubles = Double.all
  end

  def show
    @double = Double.find(params[:id])
  end

  def new
    @double = Double.new
  end

  def create
    @double = Double.new(double_params)
    if @double.save!
      redirect_to double_path(@double)
    else
      render 'new'
    end
  end

  def edit
    @double = Double.find(params[:id])
  end

  def update
    @double = Double.find(params[:id])
    if @double.update(double_params)
      redirect_to double_path(@double)
    else
      render 'edit'
    end
  end

  def destroy
    @double = Double.find(params[:id])
    @double.destroy
    redirect_to doubles_path
  end

  private

  def double_params
    params.require(:double).permit(:name, :description, :city, :country, :price_per_day, :available)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def dashboard

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doubles/edit.html.erb
<div class="container col-lg-5">
  <h1>edit <%= @double.name %></h1>
  <div>
    <%= simple_form_for @double do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :city %>
      <%= f.input :country, as: :text %>
      <%= f.input :price_per_day %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-gradient", value: "Create Lookalike" %>
    <% end %>
  </div>
</div>

app/views/doubles/index.html.erb
<h1>all lookalikes</h1>

<div class="container">
  <div class="cards">
    <% @doubles.each do |double| %>
      <%= link_to double_path(double) do %>
      <div class="card-category card-trip">
        <%= cl_image_tag double.photo.key, crop: :fill %>
        <div class="card-trip-infos">
          <div>
            <div class="double-name">
              <h2><%= double.name %></h2>
              <% if double.user_id == current_user.id %>
                <p>| <%= link_to 'Edit', edit_double_path(double) %></p>
                <p>| <%= link_to 'Delete', double_path(double), method: :delete,
                                                                    data: { confirm: "Etes-vous sûr ?" } %>
                </p>
              <% end %>
            </div>
            <p><%= double.description %></p>
          </div>
          <div>
            <h2><%= double.price_per_day %>€</h2>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/doubles/new.html.erb
<div class="container col-lg-5">
  <h1>New Lookalike</h1>
  <div>
    <%= simple_form_for @double do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :city %>
      <%= f.input :country, as: :text %>
      <%= f.input :price_per_day %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "btn btn-gradient", value: "Create Lookalike" %>
    <% end %>
  </div>
</div>

app/views/doubles/show.html.erb
<div class="container col-lg-5">
<h1><%= @double.name %> Profil</h1>
  <div class="card-trip-show">
  <%= cl_image_tag @double.photo.key, crop: :fill %>
  <div class="card-trip-infos-show">
    <div>
      <h2><%= @double.name %></h2>
      <p><%= @double.description %></p>
    </div>
    <div class="card-trip-datas-show">
      <div>
        <h5 class="card-trip-pricing">1 day : <strong><%= @double.price_per_day %>€</strong></h5>
        <h5 class="card-trip-pricing">based on <strong><%= @double.city %>, <%= @double.country %></strong></h5>
      </div>
      <%= link_to "Book now", new_double_booking_path(@double) , class: "btn btn-flat" %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoubleNeed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Looklikes", new_double_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>